version: "3.3"
services:
  candle_data_service:
    image: "lewelyn/cryptoparadise-candle_data_service:dev"
    networks:
      - localstack_network
    ports:
      - "8080:8080"
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      FLASK_ENV: development
      FLASK_APP: candle_data_service

networks:
  localstack_network:
    external: true
    name: localstack_network