version: "3.3"
services:
  candle_data_service:
    image: "lewelyn/cryptoparadise-candle_data_service:latest"
    networks:
      - localstack-net
    ports:
      - "5000:8080"
    volumes:
      - "./logging_config.yml:/app/logging_config.yml"
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      FLASK_ENV: development
      FLASK_APP: candle_data_service
      DATA_SOURCE_PROVIDER: MariaDB
      DYNAMODB_ENDPOINT_URL: "http://localstack:4566"
      MARIADB_HOST: sql-db
      RABBIT_HOSTNAME: rabbit
    entrypoint: ['sh', '-c']
    command: "'python create_environment.py && waitress-serve --call candle_data_service:create_app'"

networks:
  localstack-net:
    external: true
    name: localstack-net