version: 1
disable_existing_loggers: false
formatters:
  default:
    format: "[%(asctime)s]:%(name)s:%(module)s:%(levelname)s: %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout
    level: DEBUG
  # file:
  #   class: logging.FileHandler
  #   formatter: default
  #   filename: "{path}/service.log"
  #   level: DEBUG
root:
  level: INFO
  handlers:
  - console
loggers:
  werkzeug:
    level: INFO
  route_logger:
    level: DEBUG
  candle_data_service.candleDAO:
    level: INFO
  candle_data_service.CandlePeriodicDownloader:
    level: INFO
  candle_data_service.RabbitWrapper:
    level: WARNING
  candle_data_service.exchange:
    level: DEBUG
  candle_data_service.kinesis.consumer:
    level: INFO
  candle_data_service.KinesisPuller:
    level: DEBUG
